name: Summary test

on: workflow_dispatch

jobs:
  summary-test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: do tests
        shell: pwsh
        run: |
          "### Hello world! :rocket:" >> $env:GITHUB_STEP_SUMMARY
          ./summary-tests.ps1
