name: Summary test

on: workflow_dispatch

jobs:
  summary-test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: do tests
        shell: pwsh
        run: |
          $env:GITHUB_STEP_SUMMARY = "### Hello world! :rocket:"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- 🟢 Build successful"
