name: Test PowerShell on Ubuntu
on:
  pull_request:
    branches:
      - main

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Perform a Pester test from the skript.Tests.ps1 file
        shell: pwsh
        run: |
          Invoke-Pester skript.Tests.ps1 -Passthru